### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by hanb257** [Fixit-Davide/imu_zupt#5]
May I ask how to run this program and what is the format of the data？ Thanks!!!

**Comment by roncapat** [comment]
Hi @hanb257, can you be a little more precise?

The core logic of this node is to take a `sensor_msgs/imu` message as input, the status of the rover (boolean stating whether the robot is moving or is still) and produce as output another `sensor_msgs/imu`.

When the rover is moving, every displacement of the yaw in the input message will be reflected in the output message. The "magic" happens when the rover is still (not-moving): any drift of the input yaw will be completely cancelled from the output i.e. filtered out.

Let me know if you need something more specific. Feel also free to contribute documentation fixes or code improvements if you start to use this in a project of yours :)

**Comment by hanb257** [comment]
My dataset consists of three-axis accelerometers and three-axis gyroscopes. My data is collected by a head mounted IMU. I want to check if there is zero speed in my data. Can I use this project？

**Comment by roncapat** [comment]
Ok, now the root of your doubts is more clear to me.

This package works only on Imu messages with valid `orientation` field - i.e. orientation quaternion already estimated by some kind of filter. You may have a "smart" IMU with internal filter (such as the Xsens) or you may have a classic IMU which needs an orientation filter like the Madgwick. In any case, this nodes does not estimate the orientation given accellerometers and gyroscopes values, it just filters an already-estimated pose like a post-processing step of filtering.

You can use this project only if you obtain an orientation first from your IMU data / fill `orientation` field of the message.

**Comment by roncapat** [comment]
@hanb257 do you need something else?
